# Generated by Django 5.1.15 on 2026-02-27 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='teams.team'),
        ),
    ]
