# Generated by Django 5.1.15 on 2026-02-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_source_file_size'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knowledgebase',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gitcredential',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='git_credentials', to='teams.team'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', True)), fields=('name', 'owner'), name='unique_personal_kb_name'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebase',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('name', 'team'), name='unique_team_kb_name'),
        ),
    ]
