# Generated by Django 5.1.15 on 2026-03-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_kb_gitcredential_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbaccess',
            name='permission',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='read', max_length=5),
        ),
    ]
